### ISSUE TITLE
Multiple CMake issues

### ISSUE THREAD

**Issue by crawfxrd** [devkoriel/AwesomeCppTemplate#2]
- [`cmake_minimum_required()`](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html) must be the first command in `CMakeLists.txt`.
- If setting a version, define it in [`project()`](https://cmake.org/cmake/help/latest/command/project.html), which will set the project version variables.
- Prefer using target properties instead of directory-scoped properties.
- Don't modify `CMAKE_<LANG>_FLAGS`; use [`target_compile_options()`](https://cmake.org/cmake/help/latest/command/target_compile_options.html) (otherwise, modify them before any targets are declared)
- Move `functions.cmake` to a `cmake/` directory, set [`CMAKE_MODULE_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_MODULE_PATH.html) to search there. Specifying the `.cmake` extension for modules is not necessary.
- Command names are case insensitive, but common convention is all lowercase.

Personally,
- Don't use a variable for a target name, just use the target name. It's easier to understand.
- Related, use or create [imported targets](https://cmake.org/cmake/help/latest/command/add_library.html#imported-libraries) for dependencies to propagate build and usage requirements.
- Don't hard-code `CMAKE_VERBOSE_MAKEFILE`; set this on the command line if you need to debug the build
- Don't hard-code the compiler; set this on the command line via
```
CC=clang CXX=clang++ cmake ...
# or
cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ...
```
- Target a newer version of CMake (use CMake's provided installers or [CMake's Python distribution](https://cmake-python-distributions.readthedocs.io/en/latest/) if needed)

**Comment by devkoriel** [comment]
Thank you. I've got the similar comment at Reddit. https://www.reddit.com/r/cpp/comments/b1u9fp/i_created_c17_cmake_conan_ninja_project_template/eip61rz. I will fix the `CMakeLists.txt` less hardcoded as you said. Very helpful.
